"""add_ai_metadata_to_media

Revision ID: 7a1c719343d6
Revises: 6d904e8e0895
Create Date: 2026-07-13 15:46:21.448311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a1c719343d6'
down_revision: Union[str, Sequence[str], None] = '6d904e8e0895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('quality_score', sa.Float(), nullable=True))
    op.add_column('media', sa.Column('caption', sa.Text(), nullable=True))
    op.add_column('media', sa.Column('clip_embedding', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'clip_embedding')
    op.drop_column('media', 'caption')
    op.drop_column('media', 'quality_score')
    # ### end Alembic commands ###
